### ISSUE TITLE
Differentiating expressions inside powers

### ISSUE THREAD

**Issue by SergeiOssokine** [deshanadesai/autodiff#4]
Dear devs, 

First, thanks for the useful library!  It hits the perfect sweet spot for the problem I am considering.

I have found that differentiating an expression inside a pow call does not work correctly. Here is a MWE:

```python
c_function = "int function_test(double r, double L){ \
    double blah = pow(L+r,0.5); \
    return 0; \
}"

acorns.autodiff(c_function, 'blah', ['r','L'], func = 'function_test', output_filename = 'test_grad_back',
       output_func = 'compute_grad_back')

```

This gives as the derivatives:
```C
void compute_grad_back(double values[], int num_points, double ders[]){

	for(int i = 0; i < num_points; ++i)
	{
		double r = values[i* 2 + 0 ];
		double L = values[i* 2 + 1 ];
		ders[i*2+0]= (pow((L + r),(0.5-1)) * (0.5 * 0 + (L + r) * 0 * log((L + r)))); // df/(r) 
		ders[i*2+1]= (pow((L + r),(0.5-1)) * (0.5 * 0 + (L + r) * 0 * log((L + r)))); // df/(L) 
	}
}
```

i.e. zero for both derivatives, which is of course not the correct answer. It appears that the issue is with the ._forward_diff of the base. 

Another issues is when the base of the pow call is negative. Then the current implementation gives `nan` even when the answer should be sensible, e.g. when differentiating `pow(pr,4)` where `pr` is -1e-4.

**Comment by deshanadesai** [comment]
Hi!

Thanks for taking the time to post the issue! That was super helpful. I released an updated version of the package to conda with the bug fix for the issue with the function you posted.

If you update the package and run it, it should now return this output:

```
void compute_grad_back(double values[], int num_points, double ders[]){

	for(int i = 0; i < num_points; ++i)
	{
		double r = values[i* 2 + 0 ];
		double L = values[i* 2 + 1 ];
		ders[i*2+0]= (pow((L + r),(0.5-1)) * (0.5 * ((0) + (1)) + (L + r) * 0 * log((L + r)))); // df/(r) 
		ders[i*2+1]= (pow((L + r),(0.5-1)) * (0.5 * ((1) + (0)) + (L + r) * 0 * log((L + r)))); // df/(L) 
	}
}

```

Regarding the second issue, the code tries to calculate a log of the negative exponent (which produces the nan) even though it is multiplied by zero. I recommend compiling with the following flags enabled: -ffast-math -O3 . This should skip the calculation in an effort to optimize on the performance of the generated code.

Let me know if you get the same results!

Cheers!

**Comment by SergeiOssokine** [comment]
Hi @deshanadesai! 

Thanks for taking a look at this so quickly. Looks like the first issue is indeed solved, but only for forward mode. Running the reverse mode produces:

```C
void compute_grad_back(double values[], int num_points, double ders[]){

	for(int i = 0; i < num_points; ++i)
	{
		double r = values[i* 2 + 0 ];
		double L = values[i* 2 + 1 ];
		ders[i*2+0]= 0; // df/(r) 
		ders[i*2+1]= 0; // df/(L) 
	}
}

```

As for the second issue, thanks for pointing to the `-ffast-math` flag. However, I am not sure it works for my purposes, since those optimisations are unsafe and have resulted in issues in the past. Currently I am working on just adding an option that allows the user to specify whether the exponent should be differentiated at all. Please let me know if this is something useful and I will make a PR.

Thanks again!

**Comment by etai-shuchatowitz** [comment]
Hi @SergeiOssokine!

Thanks so much for the feedback! This is extremely helpful! 

We're aware of the issue running in reverse mode and rest assured that it's on the TODO list when we get a second. 

In regards to the second issue -- I hear your hesitation about compiling with `-ffast-math` as one loses IEEE compliance. However, in the name of simplicity I think it might be easier if we simply check if a base is negative before computing and only to take the log when it's possible (i.e. won't return a `nan`)

We're trying to keep this as bare-bones and easy to use as possible, and I think that adding a conditional to the backend reads simpler than adding another flag to pass in.

As such, we're happy to add that feature ASAP and I'll make sure to note it when we have a new release.

Thanks again so much! Good to see that this is filling a need :)

**Comment by deshanadesai** [comment]
@SergeiOssokine Sorry for the delay updating this thread! I had updated the code with a fix for the reverse mode! Hope it helps! Cheers.

**Comment by SergeiOssokine** [comment]
No worries, thanks a lot! I will test it out.

**Comment by etai-shuchatowitz** [comment]
Hi @SergeiOssokine 

I was just following up on this to see if everything was taken care of? If it is, I'll go ahead and close out this issue. 

Thanks again for the helpful feedback!
